remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: /assets/img/john_avatar6_small.png
title: Developer, Designer, Jack-of-All-Trades
description: Code can be Creative
show_downloads: true
