remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: /assets/img/john_avatar6_small.png
title: Software Engineer / Designer
description: I see DEV people
show_downloads: false
